PEFT="peft"
RL="rl"
VANILLA="vanilla"
TRAINING_TYPE_LIST=[PEFT, RL, VANILLA]

MULTIPLICATION="multi"
SUBTRACTION="subtr"
ADDITION="addi"
DIVISION="divisi"
SORTING="sorting"

TASK_LIST=[MULTIPLICATION, SUBTRACTION, ADDITION, DIVISION, SORTING]

WHOLE="whole"
DECIMAL="decimal"

NUMBER_TYPE_LIST=[WHOLE, DECIMAL]