FT="fine-tune"
RL="rl"
VANILLA="vanilla"
TRAINING_TYPE_LIST=[FT, RL, VANILLA]

MULTIPLICATION="multiplication"
SUBTRACTION="subtraction"
ADDITION="addition"
DIVISION="division"
SORTING="sorting"

TASK_LIST=[MULTIPLICATION, SUBTRACTION, ADDITION, DIVISION, SORTING]

WHOLE="whole"
DECIMAL="decimal"

NUMBER_TYPE_LIST=[WHOLE, DECIMAL]

INPUT="input"
OUTPUT="output"
TEXT="text"